application: root13test
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /style
  static_dir: Root13/style

- url: /root13
  script: Root13.helloworld.application

- url: /login
  script: Login.login.application

- url: /login/style
  static_dir: Login/style
